name: Update SL File

on:
  push:
    paths:
      - 'Sl1025.csv'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify update
        run: |
          echo "Файл Sl1025.csv был обновлен через веб-интерфейс"
